inventory/urls.py
from django.urls import path, include, reverse
from . import views
from .models import Item

urlpatterns = [
    path('', views.landing_page, name="landing_page"),
    path('view-all-items/', views.view_all_items, name="view_all_items"),
    path('create-item/', views.ItemCreateView.as_view(model=Item, success_url='/view-all-items/'), name='create_item'),
    path('item/<int:id>', views.ItemDetailView.as_view(), name="view-item"),
    path('item/<int:id>/edit/', views.ItemUpdateView.as_view(), name="edit-item"),
    path('item/<int:id>/delete/', views.ItemDeleteView.as_view(model=Item, success_url='/view-all-items/'), name="delete-item"),

    path('view-all-companies/', views.CompanyListView.as_view(), name="view-all-companies"),
    path('create-company/', views.CompanyCreateView.as_view(), name='create-company'),
    path('company/<int:company>', views.CompanyDetailView.as_view(), name='view-company'),

    path('company/<int:company>/shipments/', views.ShipmentListView.as_view(), name="view-all-shipments"),
    path('company/<int:company>/shipments/create/', views.ShipmentCreateView.as_view(), name="create-shipment"),
    path('company/<int:company>/shipments/<int:shipmentid>/items/', views.ShipmentEditItemView.as_view(), name="edit-shipment"),
    path('company/<int:company>/shipments/<int:shipmentid>/ship/', views.ShipmentShipView.as_view(), name="ship-shipment"),
    path('company/<int:company>/shipments/<int:shipmentid>/receive/', views.ShipmentReceiveView.as_view(), name="receive-shipment"),
]

logitrack/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory.urls'))
]

inventory/models.py
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.db.models import Sum

import datetime

# Create your models here.

class Item(models.Model):
    '''
        The following class model represents the items held in the logistic
        company's warehouse.

        Because the logistics company serves many different clients, each with
        their own set of items, each instance of the Item model is associated
        to a Company.

    '''
    class DimensionUnit(models.TextChoices):
        M = 'm', 'Meters'
        FT = 'ft', 'Feet'

    class WeightUnit(models.TextChoices):
        KG = 'kg', 'Kilogram'
        LB = 'lb', 'Pound'
        OZ = 'oz', 'Ounces'


    # The identifier used to differentiate between different items. Included
    # on the printing labels in the warehouse to help with picking for shipments.
    # At the time of writing, SKUs must be unique across all companies. It is
    # planned to enforce uniqueness only across items within a company, and not
    # global uniqueness as currently implemented.
    sku = models.CharField(max_length=16, unique=True)


    company = models.ForeignKey (
        'Company',
        on_delete=models.PROTECT,
        related_name="item_company"
    )

    # The common name of the item
    product_name = models.CharField(max_length=200)

    # This field tracks the quantity available to be assigned to a shipment
    quantity_available = models.PositiveIntegerField(default=0)

    # The date_create and date_last_modified fields are currently for display
    # purposes, but will eventually be used for reporting & forecasting
    date_created = models.DateTimeField(auto_now_add=True)
    date_last_modified = models.DateTimeField(auto_now=True)

    # This field is used to control whether this item should ever be included
    # in an outbound shipment
    is_shippable = models.BooleanField(default=False)

    # Fields to keep track of weight, currently used for display purposes but
    # will eventually be used to help optimize the warehouse's shipments &
    # cost structure
    weight_value = models.FloatField()
    weight_unit = models.CharField(
        max_length=2,
        choices=WeightUnit.choices,
        default=WeightUnit.KG
    )

    # Fields to keep track of dimensions - important for shipment logic that
    # will be implemented in future builds of the software
    dimension_x_value = models.FloatField()
    dimension_y_value = models.FloatField()
    dimension_z_value = models.FloatField()

    dimension_unit = models.CharField(
        max_length=2,
        choices=DimensionUnit.choices,
        default=DimensionUnit.M
    )



    def can_calculate_volume(self):
        """ A helper method to determine whether an item's volume can be calculated """
        return not (self.dimension_x_value is None or self.dimension_y_value is None or self.dimension_x_value is None)

    def total_volume_unit(self):
        """ A helper method to return the units for an item's volume """
        if not self.can_calculate_volume():
            return None
        else:
            return "%(dimension_unit)s ^ 3" % self.dimension_unit

    def total_volume_value(self):
        """ A helper method to calculate an item's total volume """
        if not self.can_calculate_volume():
            return None
        else:
            return self.dimension_x_value * self.dimension_y_value * self.dimension_z_value

    def quantity_inbound(self):
        """
        A helper method to calculate the total quantity of the item on all
        inbound shipments. Used primarily to improve user experience across the
        different views & forms within Logitrack
        """
        query = ShipmentItem.objects.filter(
            item=self,
            shipment__is_shipped=False,
            shipment__direction='IN',
            is_open=True
        ).all().aggregate(Sum('quantity'))

        result = query['quantity__sum'] if query['quantity__sum'] is not None else 0
        return result

    def quantity_allocated(self):
        """
        A helper method to calculate the total quantity of the item on
        outbound shipments for the item. Used primarily to improve user
        experience across the different views & forms within Logitrack
        """

        # Allocated quantity is the sum of the quantities of all of the
        # Shipment items that have not been shipped yet
        query = ShipmentItem.objects.filter(
            item_id=self.id,
            shipment__is_shipped=False,
            shipment__direction='OUT',
            is_open=True
        ).all().aggregate(Sum('quantity'))

        # Check for None before returning the result
        result = query['quantity__sum'] if query['quantity__sum'] is not None else 0
        return result

    def can_have_shipping_disabled(self):
        return self.quantity_allocated() == 0 and self.quantity_inbound() == 0

    def is_on_shipments(self):
        return self.quantity_allocated() > 0 or self.quantity_inbound() > 0

    def in_valid_delete_state(self):
        if self.is_on_shipments():
            return False


        return True

    def get_absolute_url(self):
        """
        A helper method used by some class-based views and templates.
        Returns the path to the Detail View for this Item instance.
        """
        view_name = 'view-item'
        return reverse(view_name, args=[self.id])

    def get_absolute_edit_url(self):
        """
        A helper method used by some class-based views and templates.
        Returns the path to the edit view for this Item instance.
        """
        view_name = 'edit-item'
        return reverse(view_name, args=[self.id])

    def get_absolute_delete_url(self):
        """
        A helper method used by some class-based views and templates.
        Returns the path to the Delete View for this Item instance.
        """
        view_name = 'delete-item'
        return reverse(view_name, args=[self.id])

    def __str__(self):
        """
        Returns the string used for the string representation
        of Item instances
        """
        fields_to_display = (self.company.name, self.sku, self.product_name)
        return '|'.join(fields_to_display)

    def delete(self):
        qty_inbound = self.quantity_inbound()
        qty_allocated = self.quantity_allocated()
        if qty_inbound > 0 or qty_allocated > 0:
            raise ValidationError(
                "You cannot delete an item that is on a shipment. Qty inbound: %(qty_inbound)s, Qty allocated: %(qty_allocated)s",
                params={'qty_inbound': qty_inbound, 'qty_allocated': qty_allocated},
                code="item_on_shipment"
            )
        else:
            super(Item, self).delete()

    def save(self, *args, **kwargs):
        self.full_clean()
        super(Item, self).save(*args, **kwargs)

    def clean(self):
        super(Item, self).clean()

        if not self.can_have_shipping_disabled() and not self.is_shippable:
            raise ValidationError(
                "You cannot set an item to be non-shippable when it is on shipments",
                code="disable_item_when_on_shipment"
            )



class Company(models.Model):
    '''
    The following class model represents the clients/different companies that
    the warehouse running the Logitrack software serves.

    At the time of writing, the model does not hold much information but
    is planned to be further developed in a future build of the software.
    '''
    # The common name of the company
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        """ Returns the string representation of Company instances """
        return self.name




class Shipment(models.Model):
    '''
        The following model captures header-level information about shipments
        to and from Logitrack's warehouse.

        Shipments can contain one or many items, represented as ShipmentItems.

        All shipments are associated to a single company, and all associated
        items on the shipment will belong to that same company as well.
    '''
    class ShipmentDirection(models.TextChoices):
        IN = 'IN', "Inbound"
        OUT = 'OUT', "Outbound"

    company = models.ForeignKey('Company', on_delete=models.PROTECT)
    to_address = models.CharField(max_length=256)


    date_created = models.DateTimeField(auto_now_add=True)

    # The date on which the shipment is expected to arrive. To be used
    # for upcoming planned Logitrack functionality.
    date_promised = models.DateTimeField()

    # The is_shipped field flags Shipment instances as either received if they
    # are inbound shipments, and 'Shipped' if they are outbound. This field also
    # drives changes to the associated item model's inventory in the case of
    # inbound shipments.
    is_shipped = models.BooleanField(default=False)
    date_shipped = models.DateTimeField(null=True, blank=True)

    # This field tracks the type of shipment, inbound or outbound.
    direction = models.CharField(
        max_length=3,
        choices=ShipmentDirection.choices,
        default=ShipmentDirection.OUT
    )

    def get_status(self):
        """
        A helper method to display the shipment status based on the Shipment's
        direction and is_shipped fields. Used primarily in templates.
        """
        if self.direction == 'OUT' and self.is_shipped:
            return 'Shipped'
        elif self.direction == 'OUT' and not self.is_shipped:
            return 'Pending Shipping'
        elif self.direction == 'IN' and self.is_shipped:
            return 'Received'
        elif self.direction == 'IN' and not self.is_shipped:
            return 'Pending Receipt'
        else:
            return 'UNKNOWN'



    def has_open_shipment_lines(self):
        """

inventory/forms.py
from django import forms
from .models import Item, Shipment, ShipmentItem, Company
from django.forms.models import inlineformset_factory, BaseInlineFormSet

"""
    The following classes override the default Django ModelForms
    behavior for the different classes within Logitrack.

    The ShipmentItemCreateFormSet is the only class within this file,
    at the time of writing, that overrides any default methods.

"""
class ItemCreateForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = [
            'sku', 'company', 'product_name', 'is_shippable', 'weight_value',
            'weight_unit', 'dimension_x_value', 'dimension_y_value',
            'dimension_z_value', 'dimension_unit', 'quantity_available'
        ]



class CompanyCreateForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = [
            'name'
        ]



class ShipmentShipForm(forms.ModelForm):
    class Meta:
        model = Shipment
        labels = {
            'date_shipped': 'Ship/Receive Date'
        }
        fields = [
            'date_shipped'
        ]




class ShipmentCreateForm(forms.ModelForm):
    class Meta:
        model = Shipment
        fields = [
            'to_address', 'date_promised', 'direction'
        ]


class ShipmentItemCreateFormSet(BaseInlineFormSet):
    """
        The following formset is used to allow users to add multiple
        ShipmentItems to a Shipment at a time.

    """
    class Meta:
        model = ShipmentItem
        fields= ['item', 'quantity']

    def __init__(self, *args, **kwargs):
        """
            This method overrides the __init__ method in order to
            restrict the Select field options to items that are both
            shippable, and belonging to this company.
            The company is passed as a keyword argument to the
            view leveraging this formset.
        """
        company_id = kwargs['instance'].company.id
        # TODO: check direction of shipment to ensure shippable items
        # are only excluded from outbound shipments.
        super(ShipmentItemCreateFormSet, self).__init__(*args, **kwargs)

        # Update each choice field to prevent selection of an item from a
        # different company.
        for form in self.forms:
            form.fields['item'].queryset = Item.objects.filter(company=company_id, is_shippable=True)

    def save(self, commit=True, *args, **kwargs):
        super(ShipmentItemCreateFormSet, self).save(*args, **kwargs)






ShipmentItemFormset = inlineformset_factory(Shipment, ShipmentItem, formset=ShipmentItemCreateFormSet, fields=('item', 'quantity'))

inventory/templates/inventory/shipments/add_items_to_shipment.html
{% extends 'inventory/base_structure.html' %}

{% block content %}
<h1>Editing {{shipment.get_direction_display}} shipment ID {{shipment.id}}</h1>

<h2>Inventory Levels</h2>
<h3>Ensure that the quantity entered for an item on a shipment is less than
or equal to its remaining inventory!</h3>

{% if items %}
<table>
  <thead>
    <th>SKU</th>
    <th>Product Name</th>
    <th>Quantity Available</th>
    <th>Quantity Inbound</th>
    <th>Quantity Allocated</th>
  </thead>
  <tbody>
    {% for item in items %}
    <tr>
      <td>{{item.sku}}</td>
      <td>{{item.product_name}}</td>
      <td>{{item.quantity_available}}</td>
      <td>{{item.quantity_inbound}}</td>
      <td>{{item.quantity_allocated}}</td>
    </tr>
      {% endfor %}
  </tbody>
</table>
{% endif %}

<form action="" method="POST" enctype="multipart/form-data">
{% for hidden_field in form.hidden_fields %}
  {{ hidden_field.errors}}
  {{ hidden_field}}
{% endfor %}
{% csrf_token %}
  {{form.management_form}}
  {{form.non_form_errors}}
  <h2>Shipment items</h2>
  {% for shipment_item_form in form.forms %}
    <hr>
    <h4>
      {% if shipment_item_form.instance.id %}
        Item: {{ shipment_item_form.instance.item.id }}
      {% else %}
        {% if form.forms|length > 1 %}
          Add another item!
        {% else %}
          Add an item!
        {% endif %}
      {% endif %}
    </h4>
    {% for hidden_field in shipment_item_form.hidden_fields %}
      {{hidden_field.errors}}
    {% endfor %}
    <table>
      {{shipment_item_form.as_table}}
    </table>
{% endfor %}
<hr>
<button type="submit" value="Save & Update Shipment">Save & Update Shipment</button>
</form>
{% endblock content %}

inventory/templates/inventory/shipments/create_shipment.html
{% extends 'inventory/base_structure.html' %}

{% block content %}



<form action="." method="POST">
  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field.errors}}
    {{ hidden_field}}
  {% endfor %}
  {% csrf_token %}

  {{form.as_p}}
  <input type="submit" value="Save & Create Shipment">
</form>

{% endblock content %}

inventory/templates/inventory/shipments/shipment_list.html
{% extends 'inventory/base_structure.html' %}

{% block content %}
<h2>Shipments for company</h2>
<a href="{% url 'create-shipment' company=view.kwargs.company %}">Create New Shipment</a>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Date Created</th>
      <th>Ship/Receive Date</th>
      <th>Direction</th>
      <th>To Address</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for shipment in object_list %}
    <tr>
        <td> {{shipment.get_status}}  </td>
        <td>{{ shipment.date_created }}</td>
        <td>{{ shipment.date_shipped }}</td>
        <td>{{ shipment.direction }}</td>
        <td>{{ shipment.to_address }}</td>
        <td>
          {% if shipment.date_shipped %}
          ---------
          {% else %}
            <a href="{% url 'edit-shipment' company=shipment.company.id shipmentid=shipment.id %}">Edit</a>
            {% if shipment.direction == "OUT" %}
              |<a href="{% url 'ship-shipment' company=view.kwargs.company shipmentid=shipment.id %}">Ship</a>
            {% elif shipment.direction == "IN" %}
              |<a href="{% url 'receive-shipment' company=view.kwargs.company shipmentid=shipment.id %}">Receive</a>
            {% endif %}
          {% endif %}
        </td>

    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock content %}

inventory/templates/inventory/shipments/shipment_receive.html
{% extends 'inventory/base_structure.html' %}


{% block content %}

<h1>Receiving Shipment {{object.id}}</h1>
<h2>Header Details</h2>
<table>
  <thead>
    <tr>
      <th>Shipment ID</th>
      <th>For Company</th>
      <th>Date Created</th>
      <th>Date Promised</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>{{object.id}}</th>
      <th>{{object.company.name}}</th>
      <th>{{object.date_created}}</th>
      <th>{{object.date_received}}</th>
    </tr>
  </tbody>
</table>
<hr>
<h2>Footer Details</h2>
  <table>
    <thead>
      <th>SKU</th>
      <th>Product Name</th>
      <th>Quantity</th>
    </thead>
    <tbody>
      {% for shipment_item in shipmentItems %}
      <tr>
        <td>{{shipment_item.item.sku}}</td>
        <td>{{shipment_item.item.product_name}}</td>
        <td>{{shipment_item.quantity}}</td>
      </tr>
        {% endfor %}
    </tbody>
  </table>

<hr>
<form action="." method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Receive Shipment">
</form>

{% endblock content %}

inventory/templates/inventory/shipments/shipment_ship.html
{% extends 'inventory/base_structure.html' %}


{% block content %}

<h1>Shipping Shipment {{object.id}}</h1>
<h2>Header Details</h2>
<table>
  <thead>
    <tr>
      <th>Shipment ID</th>
      <th>For Company</th>
      <th>Date Created</th>
      <th>Date Promised</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>{{object.id}}</th>
      <th>{{object.company.name}}</th>
      <th>{{object.date_created}}</th>
      <th>{{object.date_received}}</th>
    </tr>
  </tbody>
</table>
<hr>
<h2>Footer Details</h2>
  <table>
    <thead>
      <th>SKU</th>
      <th>Product Name</th>
      <th>Quantity</th>
    </thead>
    <tbody>
      {% for shipment_item in shipmentItems %}
      <tr>
        <td>{{shipment_item.item.sku}}</td>
        <td>{{shipment_item.item.product_name}}</td>
        <td>{{shipment_item.quantity}}</td>
      </tr>
        {% endfor %}
    </tbody>
  </table>

<hr>
<form action="." method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit" value="Ship Shipment">
</form>

{% endblock content %}